<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page' => '(default page)',
    'page_articles' => 'Articles page',
    'page_contact' => 'Contact page',
    'page_home' => 'Home page',
    'page_single_article' => 'Single article page',
  ),
);


/* Auto generated by Themes Administration on : 2015.04.21 09:27:21 */
